name: Test
# This workflow is triggered on push to the repository.
on: [release]

jobs:   
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    # - uses: ./ # Uses an action in the root directory
    - name: Hello world action step
      id: hello
      uses: emiliano84/Toolkit.Docs/.github/actions/hello-world@dev
      with:
        who-to-greet: '${{secrets.GITHUB_TOKEN}}'
    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time aaa ${{ steps.hello.outputs.list }}"