name: Update Folder To Gh-pages
# This workflow is triggered on push to the repository.
on: [push]

jobs:   
  clone_and_push:
    runs-on: windows-latest
    name: Clone And Push
    steps:
    - uses: actions/checkout@v1   
    
    - name: Git Config email
      run: git config --global user.email "emiliano84@github.com"
      shell: bash

    - name: Git Config name
      run: git config --global user.name "DocFx Bot"
      shell: bash

    - name: Git Config remote.origin.url
      run: git config --global remote.origin.url "https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/myRepo.git"
      shell: bash
      # https://stackoverflow.com/questions/5343068/is-there-a-way-to-cache-github-credentials-for-pushing-commits
        
    - name: git remote add origin
      run: git remote add origin https://github.com/emiliano84/myRepo
      continue-on-error: true
      shell: bash
      # shell: powershell

    - name: git fetch origin
      run: git fetch origin
      shell: bash

    - name: git checkout master
      run: git checkout master
      shell: bash

    - name: git subtree add
      run: git subtree add --prefix docs origin/gh-pages  
      continue-on-error: true
      shell: bash

    - name: Docfx
      id: docfx
      run: ".github/scripts/docfx.bat"
      shell: bash

  #  docfx metadata docfx_project/docfx.json
  #  docfx build docfx_project/docfx.json -o docs

    - name: Git Add docs
      run: git add docs/* -f
      shell: bash

    - name: Git Commit
      run: git commit -m "Docs"
      shell: bash
      
    # - name: Git Push
    #   run: git subtree push --prefix docs origin gh-pages
    # shell: bash

    # - name: Git Push
    #   run: git push origin `git subtree split --prefix docs gh-pages` gh-pages --force
    #   shell: bash

    # create a local gh-pages branch containing the splitted output folder
    - name: Git subtree
      run: git subtree split --prefix docs -b gh-pages 
      shell: bash
    # force the push of the gh-pages branch to the remote gh-pages branch at origin
    - name: Git Push
      run: git push -f https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/myRepo.git gh-pages:gh-pages
      shell: bash    

    # - name: git reset --hard
    #   run: git reset --hard   

    # - name: Git delete branch
    #   run: git push https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git :gh-pages
    
    # - name: Git Push
    #   run: git push -f

  # job2:
  #   needs: job1
