name: Update Folder To Gh-pages
# This workflow is triggered on push to the repository.
on: [push]

jobs:   
  clone_and_push:
    runs-on: windows-latest
    name: Clone And Push
    steps:
    - uses: actions/checkout@v1   
    
    - name: Git Config email
      run: git config --global user.email "emiliano84@github.com"
    - name: Git Config name
      run: git config --global user.name "DocFx Bot"
    - name: Git Config remote.origin.url
      run: git config --global remote.origin.url "https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/myRepo.git"
      # https://stackoverflow.com/questions/5343068/is-there-a-way-to-cache-github-credentials-for-pushing-commits
    
    - name: Git Add docs
      run: git add docs/* -f
    - name: Git Commit
      run: git commit -m "Docs"

    - name: Git Subtree
      run: git subtree split --prefix docs -b gh-pages

    # - name: git checkout --orphan gh-pages
    #   run: git checkout --orphan gh-pages   

    # - name: git reset --hard
    #   run: git reset --hard 
    # - name: git remote add origin https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git
    #   run: git remote add origin 
    # - name: git fetch origin
    #   run: git fetch origin
    # - name: git subtree add
    #   run: git subtree add --prefix docs origin/gh-pages    
    # - name: Git delete branch
    #   run: git push https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git :gh-pages

    
    # - name: Git Push
    #   run: git push -f

    # - name: Git Push
    #   run: git subtree push --prefix docs https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git gh-pages
      # run: git push origin `git subtree split --prefix docs master`:gh-pages --force
      # run: git push https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git gh-pages --force 