name: Windows Test
# This workflow is triggered on push to the repository.
on: [push]

jobs:   
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Git Clone
      run: git clone https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.git ../Toolkit
    # - name: Hello world action step
    #   id: hello
    #   run: echo "hello world"
    # - name: Dir
    #   id: dir2
    #   run: dir   
    
    - name: Docfx
      id: docfx
      run: ".github/scripts/docfx.bat"

    - name: Git Config email
      run: git config --global user.email "emiliano84@github.com"
    - name: Git Config name
      run: git config --global user.name "DocFx Bot"

    - name: git checkout --orphan gh-pages
      run: git checkout --orphan gh-pages   

    # - name: git reset --hard
    #   run: git reset --hard 
    # - name: git remote add origin https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git
    #   run: git remote add origin 
    # - name: git fetch origin
    #   run: git fetch origin
    # - name: git subtree add
    #   run: git subtree add --prefix docs origin/gh-pages    
    # - name: Git delete branch
    #   run: git push https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git :gh-pages

    - name: Git Add docs
      run: git add docs/* -f
    - name: Git Commit
      run: git commit -m "Docs"

    - name: Git Subtree
      run: git subtree split --prefix docs -b gh-pages # create a local gh-pages branch containing the splitted output folder
    - name: Git Push
      run: git push -f https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git gh-pages:gh-pages # force the push of the gh-pages branch to the remote gh-pages branch at origin

    # - name: Git Push
    #   run: git subtree push --prefix docs https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git gh-pages
      # run: git push origin `git subtree split --prefix docs master`:gh-pages --force
      # run: git push https://emiliano84:${{secrets.GITHUB_TOKEN}}@github.com/emiliano84/Toolkit.Docs.git gh-pages --force 